# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  pulumi: pulumi/pulumi@2.0.0
  gcp-cli: circleci/gcp-cli@2.4.0

jobs:
  build:
    docker:
      - image: 'cimg/node:17.5.0'
    working_directory: ~/repo/
    steps:
      - checkout
      - pulumi/login:
          version: 3.24.1
      - run:
          command: |
            npm install
      - pulumi/update:
          stack: Mikek_ee/gcloud/dev      
 

